# GPU cluster example
# This is a cluster with one master node and two worker nodes

machine-sku:
  master-machine: # define a machine sku
    # the resource requirements for all the machines of this sku
    # We use the same memory format as Kubernetes, e.g. Gi, Mi
    # Reference: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-memory
    mem: 500Gi
    cpu:
      # the number of CPU vcores
      vcore: 64
  a800-machine:
    computing-device:
      # For `type`, please follow the same format specified in device plugin.
      # For example, `nvidia.com/gpu` is for NVIDIA GPU, `amd.com/gpu` is for AMD GPU,
      # and `enflame.com/dtu` is for Enflame DTU.
      # Reference: https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/
      type: nvidia.com/gpu
      model: A800
      count: 8
    mem: 950Gi
    cpu:
      vcore: 120

machine-list:
  - hostname: 192.168.99.9 # name of the machine, **do not** use upper case alphabet letters for hostname
    hostip: 192.168.99.9
    machine-type: master-machine # only one master-machine supported
    pai-master: "true"
  - hostname: 192.168.112.9
    hostip: 192.168.112.9
    machine-type: a800-machine
    pai-worker: "true"
  - hostname: 192.168.112.10
    hostip: 192.168.112.10
    machine-type: a800-machine
    pai-worker: "true"


